version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    ignore:
      - dependency-name: "typescript"
        versions:
          - "<5.6.0"
